# Generated by Django 5.2.7 on 2025-10-28 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirdropTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('follow_twitter', 'Follow Twitter'), ('join_telegram', 'Join Telegram'), ('subscribe_youtube', 'Subscribe YouTube'), ('retweet', 'Retweet Post')], max_length=50)),
                ('points_reward', models.IntegerField(default=100)),
                ('verification_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AirdropUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('wallet_address', models.CharField(blank=True, max_length=100)),
                ('total_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('proof_url', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('points_awarded', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airdrop.airdroptask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airdrop.airdropuser')),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
