# Generated by Django 5.2.7 on 2025-10-28 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdropuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='airdropuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='airdrop.airdropuser'),
        ),
    ]
